version: "3.5"
services:
  nodered:
    container_name: nodered
    image: nodered/node-red:latest-22
    ports:
      - 1880:1880
    volumes:
      - ./data:/data
      - ./settings.js:/data/settings.js
    environment:
      TZ: "America/Sao_Paulo"
    links:
      - postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: ypi
      POSTGRES_USER: yaferreira
      POSTGRES_PASSWORD: yuri
      TZ: "America/Sao_Paulo"
      PGTZ: "America/Sao_Paulo"
    ports:
      - "5432"

  adminer:
    image: adminer
    container_name: ypi_adminer
    depends_on:
      - postgres
    ports:
      - "8082:8080"
